source/Object.cpp, source/Object.h, source/Platform.cpp, source/Platform.h, source/SSBGameScene.cpp, source/SSBGameScene.h
Method to enable customizable platform creation
=> Platform Creation

source/SSBDudeModel.cpp, source/SSBDudeModel.h, source/SSBGameScene.cpp
Implemented Gliding and proper physics scaling.
=> Glide branch

source/Platform.cpp, source/Platform.h, source/SSBGameScene.cpp, source/SSBGameScene.h
added moving platforms  (to be fixed: normalization and whether to allow movements in both direction)
=> moving platform (need to fix direction normalization)

source/SSBGameScene.cpp
- Commented out code related to wall since this is not currently used
=> Fix VScode wall error 

source/SSBGameScene.cpp, source/SSBGameScene.h
- Traps are limited to 1 per round
- Basic inventory UI (darkens when you can't place any more)
=> Added trap limit and basic inventory UI

source/SSBGameScene.h
=> Updated moving wall

source/SSBDudeModel.cpp
Jumping is easier to control now
=> Fixed jumping control

source/SSBDudeModel.cpp, source/SSBGameScene.cpp
- the slinging mechanic has been removed. The SSBInput code has not been changed in case we need those methods for something else, but slinging itself has been removed
=> Slinging has been destroyed

source/SSBDudeModel.cpp, source/SSBDudeModel.h, source/SSBGameScene.cpp, source/SSBInput.cpp, source/SSBInput.h
Tap and hold middair to glide.
=> Implemented Rudimentary Gliding

assets/json/assets.json, assets/json/test2.json, source/LevelModel.cpp, source/Object.h, source/Platform.cpp, source/Platform.h, source/SSBGameScene.cpp, source/SSBGameScene.h, source/Spike.cpp, source/Spike.h, source/Treasure.cpp, source/Treasure.h, source/WindObstacle.cpp, source/WindObstacle.h
- Every object now has a _jsonType attribute which is a string indicating which type of object it is (as labeled in the JSON file)
- Updated the level so that all its objects contain the string
-  Updated all objects to add its type to the map that is used to generate a JSON file
=> Support for JsonType string

source/Constants.h, source/NPHostScene.h, source/NetworkController.cpp, source/NetworkController.h, source/SSBApp.cpp, source/SSBApp.h, source/SSBDudeModel.h, source/SSBGameScene.cpp, source/SSBGameScene.h
Refactored the code base so that all networking logic is in its own controller. 
Modified Constants.h to hold all texture names, etc. needed for object creation and physics.
Also cleaned up a lot of commented out code.
=> Angelica network refactor

assets/widgets/start.json, source/SSBApp.cpp, source/StartScene.cpp, source/StartScene.h
Add level editor button to start screen
=> Add level editor button to UI

source/NetworkController.cpp, source/SSBDudeModel.cpp
PLayer hitbox made smaller and offset to fit between small spaces
=> Rescaled player hitbox

source/BuildPhaseController.cpp, source/BuildPhaseScene.cpp, source/BuildPhaseUIScene.cpp, source/BuildPhaseUIScene.h, source/Constants.h, source/MenuScene.cpp, source/MenuScene.h, source/MovePhaseController.cpp, source/MovePhaseController.h, source/MovePhaseScene.cpp, source/MovePhaseScene.h, source/MovePhaseUIScene.cpp, source/MovePhaseUIScene.h, source/NetworkController.cpp, source/NetworkController.h, source/ObjectController.cpp, source/PlayerModel.cpp, source/PlayerModel.h, source/SSBGameController.cpp, source/SSBGameController.h
All instances of dudemodel replaced with playermodel
=> Dude model refactored

source/MovePhaseScene.cpp, source/NPClientScene.cpp, source/NPClientScene.h, source/NPHostScene.cpp, source/NPHostScene.h, source/SSBApp.cpp, source/ScoreController.h
Properly reset the Client and Host scenes.
The treasure is in the correct position.
=> Minor Fixes

assets/widgets/host.json, source/NPHostScene.cpp
- fix overlapping no. of players icon
- changed room id code font and color to fit
=> Implement minor host screen fix

assets/json/assets.json
- fix capitalization in assets.json
=> fix assets json

source/BuildPhaseController.cpp, source/LevelEditorController.cpp, source/Mushroom.cpp, source/NetworkController.cpp, source/Platform.cpp, source/Platform.h, source/Thorn.cpp, source/WindObstacle.cpp
- Fixed object positioning to be correct with object placing / moving logic.
- Fixed positioning of wind object gust on update.
=> Fixed object offsets + wind object updates

source/BuildPhaseController.cpp
- Build phase camera moves by dragging objects close to edge
- Build phase camera has more acceleration
=> Camera Updates

source/PlayerModel.cpp, source/PlayerModel.h
Adjusted some variables to make player a little less powerful.
=> Adjusted player variables

source/TransitionScene.cpp
=> Fixed Transitions

source/Platform.cpp
- Moving platform animations networked
=> Updating Moving Platform

source/NetworkController.cpp, source/Thorn.cpp, source/Thorn.h
- Thorn is now able to be moved and synced among players.
=> Fixed thorn networking during build phase

source/LevelSelectScene.cpp, source/Treasure.h
Sped up treasure steal cooldown
=> Angelica network fixes

source/StartScene.cpp
=> Got rid of level editor

source/SSBInput.cpp
=> Disabled Debug Mode

source/LevelSelectScene.cpp
removed duplicate sounds (hopefully, I can't test it, but I'm pretty sure this line is the issue)
=> Sound Bugfix

source/NetworkController.cpp, source/SSBApp.cpp, source/ScoreController.h
Pressing start after quit works now
=> Can press start after quit
